apiVersion: v1
kind: Secret
metadata:
  name: gitlab-secret
  namespace: 1212-dashboard
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {"auths":{"gitlab.nso.mn:5050":{"username":"REPLACE_ME","password":"REPLACE_ME","email":"REPLACE_ME","auth":"REPLACE_ME"}}}
